import json

with open('SpanishSentences.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

# Translations mapping
# For Chinese and Korean, 'palabras' must be in English.
# For Italian, French, German, 'palabras' and 'oracion' are in their respective languages.

# Let's define translations for each item index 0 to 52 (53 items total)

# Chinese data
zh_data = {
    "root": [
        {"palabras": "hunger pasta", "oracion": "我很饿，我想吃面条。"},
        {"palabras": "change channel", "oracion": "我想换电视频道。"},
        {"palabras": "thirst", "oracion": "我很渴，需要喝点东西。"},
        {"palabras": "sleep", "oracion": "困"},
        {"palabras": "hunger apple pear", "oracion": "我很饿，想吃一个苹果和一个梨。"},
        {"palabras": "hunger soup", "oracion": "我很饿，想喝汤。"},
        {"palabras": "hunger macaroni cheese", "oracion": "我很饿，想吃奶酪通心粉。"},
        {"palabras": "thirst water", "oracion": "我很渴，需要喝水。"},
        {"palabras": "sleepy", "oracion": "我困了。"},
        {"palabras": "sleepy go to sleep", "oracion": "我困了，需要去睡觉。"},
        {"palabras": "need medication", "oracion": "我需要吃药。"},
        {"palabras": "need change channel", "oracion": "我需要换个频道。"},
        {"palabras": "channel change", "oracion": "我需要换频道。"},
        {"palabras": "hunger burger fries", "oracion": "我很饿，想吃汉堡和薯条。"},
        {"palabras": "turn on radio", "oracion": "我想打开收音机。"},
        {"palabras": "change station", "oracion": "我想换收音机台。"},
        {"palabras": "bathroom", "oracion": "卫生间"},
        {"palabras": "bathroom", "oracion": "我需要去卫生间。"},
        {"palabras": "pain", "oracion": "我感到疼痛。"},
        {"palabras": "headache", "oracion": "我头痛。"},
        {"palabras": "knee pain", "oracion": "我膝盖疼。"},
        {"palabras": "nervous", "oracion": "我感到紧张。"},
        {"palabras": "take a bath", "oracion": "我需要洗澡。"},
        {"palabras": "hello", "oracion": "你好，你好吗？"},
        {"palabras": "how are you", "oracion": "你好吗？"},
        {"palabras": "glad", "oracion": "很高兴。"},
        {"palabras": "sad", "oracion": "我感到难过。"},
        {"palabras": "happy", "oracion": "我感到高兴。"},
        {"palabras": "hello", "oracion": "我很好，你呢"},
        {"palabras": "good and you", "oracion": "很好，你呢？"},
        {"palabras": "lunch soup", "oracion": "我想吃午餐汤"},
        {"palabras": "dinner", "oracion": "我想吃晚餐。"},
        {"palabras": "breakfast", "oracion": "我想吃早餐。"},
        {"palabras": "urinate", "oracion": "我需要去洗手间。"},
        {"palabras": "defecate", "oracion": "我需要去洗手间。"},
        {"palabras": "drink", "oracion": "我需要喝点东西。"},
        {"palabras": "drink water", "oracion": "我需要喝水。"},
        {"palabras": "drink wine", "oracion": "我想喝一杯葡萄酒。"},
        {"palabras": "turn off television", "oracion": "我想关掉电视。"},
        {"palabras": "turn off fan", "oracion": "我想关掉风扇。"},
        {"palabras": "turn on fan", "oracion": "我想打开风扇。"},
        {"palabras": "grandma hunger", "oracion": "奶奶饿了。"},
        {"palabras": "dog hunger", "oracion": "狗饿了。"},
        {"palabras": "cat hunger", "oracion": "猫饿了。"},
        {"palabras": "read", "oracion": "我需要阅读。"},
        {"palabras": "read book", "oracion": "我想看书。"},
        {"palabras": "pass book", "oracion": "你能把书递给我吗？"},
        {"palabras": "music", "oracion": "我想听音乐。"},
        {"palabras": "change song", "oracion": "我想换首歌。"},
        {"palabras": "rewind song", "oracion": "我想倒回上一首歌。"},
        {"palabras": "fast forward song", "oracion": "我想快进这首歌。"},
        {"palabras": "battery charge", "oracion": "我需要给电池充电。"},
        {"palabras": "turn on light", "oracion": "我想开灯。"},
        {"palabras": "turn off light", "oracion": "我想关灯。"},
        {"palabras": "itchy back", "oracion": "我背部发痒。"},
        {"palabras": "foot pain", "oracion": "我脚疼。"},
        {"palabras": "increase music volume", "oracion": "我想调高音乐音量。"},
        {"palabras": "need ophthalmologist", "oracion": "我需要去看眼科医生。"},
        {"palabras": "send message", "oracion": "我需要发信息。"},
        {"palabras": "send message mom", "oracion": "我需要给我妈妈发信息。"},
        {"palabras": "visit", "oracion": "我需要去拜访某人。"},
        {"palabras": "time", "oracion": "几点钟了？"},
        {"palabras": "one two three", "oracion": "123"}
    ]
}

# Korean data
ko_data = {
    "root": [
        {"palabras": "hunger pasta", "oracion": "배고파요, 파스타 먹고 싶어요."},
        {"palabras": "change channel", "oracion": "TV 채널을 바꾸고 싶어요."},
        {"palabras": "thirst", "oracion": "목이 마르, 뭐 좀 마시고 싶어요."},
        {"palabras": "sleep", "oracion": "졸려요"},
        {"palabras": "hunger apple pear", "oracion": "배고파요, 사과랑 배 먹고 싶어요"},
        {"palabras": "hunger soup", "oracion": "배고파요, 수프 먹고 싶어요."},
        {"palabras": "hunger macaroni cheese", "oracion": "배고파요, 치즈 마카로니 먹고 싶어요."},
        {"palabras": "thirst water", "oracion": "목이 마르, 물 마셔야 해요."},
        {"palabras": "sleepy", "oracion": "졸려요."},
        {"palabras": "sleepy go to sleep", "oracion": "졸려요, 자러 가야 해요."},
        {"palabras": "need medication", "oracion": "약을 먹어야 해요"},
        {"palabras": "need change channel", "oracion": "채널을 바꿔야 해요."},
        {"palabras": "channel change", "oracion": "채널을 바꿔야 해요"},
        {"palabras": "hunger burger fries", "oracion": "배고파요, 햄버거랑 감자튀김 먹고 싶어요."},
        {"palabras": "turn on radio", "oracion": "라디오를 켜고 싶어요."},
        {"palabras": "change station", "oracion": "라디오 방송국을 바꾸고 싶어요."},
        {"palabras": "bathroom", "oracion": "화장실"},
        {"palabras": "bathroom", "oracion": "화장실에 가야 해요."},
        {"palabras": "pain", "oracion": "아파요."},
        {"palabras": "headache", "oracion": "머리가 아파요."},
        {"palabras": "knee pain", "oracion": "무릎이 아파요."},
        {"palabras": "nervous", "oracion": "긴장돼요."},
        {"palabras": "take a bath", "oracion": "목욕을 해야 해요."},
        {"palabras": "hello", "oracion": "안녕하세요, 어떻게 지내세요?"},
        {"palabras": "how are you", "oracion": "어떻게 지내세요?"},
        {"palabras": "glad", "oracion": "다행이네요."},
        {"palabras": "sad", "oracion": "슬퍼요."},
        {"palabras": "happy", "oracion": "행복해요."},
        {"palabras": "hello", "oracion": "잘 지내요, 당신은요"},
        {"palabras": "good and you", "oracion": "잘 지내요, 당신은요?"},
        {"palabras": "lunch soup", "oracion": "점심으로 수프를 먹고 싶어요"},
        {"palabras": "dinner", "oracion": "저녁을 먹고 싶어요."},
        {"palabras": "breakfast", "oracion": "아침을 먹고 싶어요."},
        {"palabras": "urinate", "oracion": "화장실에 가야 해요."},
        {"palabras": "defecate", "oracion": "화장실에 가야 해요."},
        {"palabras": "drink", "oracion": "뭐 좀 마시고 싶어요."},
        {"palabras": "drink water", "oracion": "물 마셔야 해요."},
        {"palabras": "drink wine", "oracion": "와인 한 잔 마시고 싶어요."},
        {"palabras": "turn off television", "oracion": "TV를 끄고 싶어요."},
        {"palabras": "turn off fan", "oracion": "선풍기를 끄고 싶어요."},
        {"palabras": "turn on fan", "oracion": "선풍기를 켜고 싶어요."},
        {"palabras": "grandma hunger", "oracion": "할머니가 배고프대요."},
        {"palabras": "dog hunger", "oracion": "강아지가 배고파요"},
        {"palabras": "cat hunger", "oracion": "고양이가 배고파요."},
        {"palabras": "read", "oracion": "책을 읽어야 해요."},
        {"palabras": "read book", "oracion": "책을 읽고 싶어요."},
        {"palabras": "pass book", "oracion": "책 좀 건네주시겠어요?"},
        {"palabras": "music", "oracion": "음악을 듣고 싶어요."},
        {"palabras": "change song", "oracion": "노래를 바꾸고 싶어요."},
        {"palabras": "rewind song", "oracion": "이전 노래로 돌아가고 싶어요."},
        {"palabras": "fast forward song", "oracion": "노래를 빨리감기하고 싶어요."},
        {"palabras": "battery charge", "oracion": "배터리를 충전해야 해요."},
        {"palabras": "turn on light", "oracion": "불을 켜고 싶어요."},
        {"palabras": "turn off light", "oracion": "불을 끄고 싶어요."},
        {"palabras": "itchy back", "oracion": "등이 가려워요."},
        {"palabras": "foot pain", "oracion": "발이 아파요."},
        {"palabras": "increase music volume", "oracion": "음악 소리를 키우고 싶어요."},
        {"palabras": "need ophthalmologist", "oracion": "안과에 가야 해요."},
        {"palabras": "send message", "oracion": "메시지를 보내야 해요."},
        {"palabras": "send message mom", "oracion": "엄마에게 메시지를 보내야 해요"},
        {"palabras": "visit", "oracion": "누군가를 방문해야 해요."},
        {"palabras": "time", "oracion": "지금 몇 시예요?"},
        {"palabras": "one two three", "oracion": "123"}
    ]
}

# Italian data
it_data = {
    "root": [
        {"palabras": "fame pasta", "oracion": "Ho fame, voglio la pasta."},
        {"palabras": "cambiare canale", "oracion": "Voglio cambiare il canale della televisione."},
        {"palabras": "sete", "oracion": "Ho sete, ho bisogno di bere qualcosa."},
        {"palabras": "dormire", "oracion": "sonno"},
        {"palabras": "fame mela pera", "oracion": "Ho fame, voglio una mela e una pera"},
        {"palabras": "fame zuppa", "oracion": "Ho fame, voglio una zuppa."},
        {"palabras": "fame maccheroni formaggio", "oracion": "Ho fame, voglio i maccheroni al formaggio."},
        {"palabras": "sete acqua", "oracion": "Ho sete, ho bisogno di bere acqua."},
        {"palabras": "sonno", "oracion": "Ho sonno."},
        {"palabras": "sonno dormire", "oracion": "Ho sonno, devo andare a dormire."},
        {"palabras": "ho bisogno di medicina", "oracion": "Ho bisogno di prendere le mie medicine"},
        {"palabras": "ho bisogno di cambiare canale", "oracion": "Ho bisogno di cambiare canale."},
        {"palabras": "canale cambiare", "oracion": "Ho bisogno di cambiare il canale"},
        {"palabras": "fame hamburger patatine", "oracion": "Ho fame, voglio un hamburger con le patatine."},
        {"palabras": "accendere radio", "oracion": "Voglio accendere la radio."},
        {"palabras": "cambiare stazione", "oracion": "Voglio cambiare la stazione radio."},
        {"palabras": "bagno", "oracion": "bagno"},
        {"palabras": "bagno", "oracion": "Ho bisogno di andare in bagno."},
        {"palabras": "dolore", "oracion": "Ho un dolore."},
        {"palabras": "dolore testa", "oracion": "Mi fa male la testa."},
        {"palabras": "dolore ginocchio", "oracion": "Ho dolore al ginocchio."},
        {"palabras": "nervoso", "oracion": "Mi sento nervoso."},
        {"palabras": "fare il bagno", "oracion": "Ho bisogno di fare il bagno."},
        {"palabras": "Ciao", "oracion": "Ciao, come stai?"},
        {"palabras": "come stai", "oracion": "Come stai tu?"},
        {"palabras": "felice mi alegro", "oracion": "Mi fa piacere."},
        {"palabras": "triste", "oracion": "Mi sento triste."},
        {"palabras": "felice", "oracion": "Mi sento felice."},
        {"palabras": "ciao", "oracion": "bene tu"},
        {"palabras": "bene tu", "oracion": "Bene, e tu?"},
        {"palabras": "pranzo zuppa", "oracion": "Voglio pranzare con una zuppa"},
        {"palabras": "cena", "oracion": "Voglio cenare."},
        {"palabras": "fare colazione", "oracion": "Voglio fare colazione."},
        {"palabras": "orinare", "oracion": "Ho bisogno di andare in bagno."},
        {"palabras": "defecare", "oracion": "Ho bisogno di andare in bagno."},
        {"palabras": "bere", "oracion": "Ho bisogno di bere qualcosa."},
        {"palabras": "bere acqua", "oracion": "Ho bisogno di bere acqua."},
        {"palabras": "bere vino", "oracion": "Voglio bere un bicchiere di vino."},
        {"palabras": "spegnere televisione", "oracion": "Voglio spegnere la televisione."},
        {"palabras": "spegnere ventilatore", "oracion": "Voglio spegnere il ventilatore."},
        {"palabras": "accendere ventilatore", "oracion": "Voglio accendere il ventilatore."},
        {"palabras": "nonna fame", "oracion": "La nonna ha fame."},
        {"palabras": "cane fame", "oracion": "Il cane ha fame"},
        {"palabras": "gatto fame", "oracion": "Il gatto ha fame."},
        {"palabras": "leggere", "oracion": "Ho bisogno di leggere."},
        {"palabras": "leggere libro", "oracion": "Voglio leggere un libro."},
        {"palabras": "passare libro", "oracion": "Potresti passarmi il libro?"},
        {"palabras": "musica", "oracion": "Voglio ascoltare la musica."},
        {"palabras": "cambiare canzone", "oracion": "Voglio cambiare canzone."},
        {"palabras": "tornare indietro canzone", "oracion": "Voglio tornare alla canzone precedente."},
        {"palabras": "andare avanti canzone", "oracion": "Voglio mandare avanti la canzone."},
        {"palabras": "batteria caricare", "oracion": "Ho bisogno di caricare la batteria."},
        {"palabras": "accendere luce", "oracion": "Voglio accendere la luce."},
        {"palabras": "spegnere luce", "oracion": "Voglio spegnere la luce."},
        {"palabras": "prurito schiena", "oracion": "Mi prurito alla schiena."},
        {"palabras": "dolore piede", "oracion": "Ho un dolore al piede."},
        {"palabras": "alzare volume musica", "oracion": "Voglio alzare il volume della musica."},
        {"palabras": "bisogno oculista", "oracion": "Ho bisogno di andare dall'oculista."},
        {"palabras": "mandare messaggio", "oracion": "Ho bisogno di mandare un messaggio."},
        {"palabras": "mandare messaggio mamma", "oracion": "Ho bisogno di mandare un messaggio alla mia mamma"},
        {"palabras": "visitare", "oracion": "Ho bisogno di visitare qualcuno."},
        {"palabras": "ora", "oracion": "Che ore sono?"},
        {"palabras": "uno due tre", "oracion": "123"}
    ]
}

# French data
fr_data = {
    "root": [
        {"palabras": "faim pâtes", "oracion": "J'ai faim, je veux des pâtes."},
        {"palabras": "changer chaîne", "oracion": "Je veux changer de chaîne de télévision."},
        {"palabras": "soif", "oracion": "J'ai soif, j'ai besoin de boire quelque chose."},
        {"palabras": "dormir", "oracion": "sommeil"},
        {"palabras": "faim pomme poire", "oracion": "J'ai faim, je veux une pomme et une poire"},
        {"palabras": "faim soupe", "oracion": "J'ai faim, je veux une soupe."},
        {"palabras": "faim coquillettes fromage", "oracion": "J'ai faim, je veux des macaroni au fromage."},
        {"palabras": "soif eau", "oracion": "J'ai soif, j'ai besoin de boire de l'eau."},
        {"palabras": "sommeil", "oracion": "J'ai sommeil."},
        {"palabras": "sommeil dormir", "oracion": "J'ai sommeil, je dois aller dormir."},
        {"palabras": "besoin médicament", "oracion": "J'ai besoin de prendre mes médicaments"},
        {"palabras": "besoin changer chaîne", "oracion": "J'ai besoin de changer de chaîne."},
        {"palabras": "chaîne changer", "oracion": "J'ai besoin de changer la chaîne"},
        {"palabras": "faim hamburger frites", "oracion": "J'ai faim, je veux un hamburger avec des frites."},
        {"palabras": "allumer radio", "oracion": "Je veux allumer la radio."},
        {"palabras": "changer station", "oracion": "Je veux changer de station de radio."},
        {"palabras": "toilettes", "oracion": "toilettes"},
        {"palabras": "toilettes", "oracion": "J'ai besoin d'aller aux toilettes."},
        {"palabras": "douleur", "oracion": "J'ai une douleur."},
        {"palabras": "douleur tête", "oracion": "J'ai mal à la tête."},
        {"palabras": "douleur genou", "oracion": "J'ai mal au genou."},
        {"palabras": "nerveux", "oracion": "Je me sens nerveux."},
        {"palabras": "prendre un bain", "oracion": "J'ai besoin de prendre un bain."},
        {"palabras": "Bonjour", "oracion": "Bonjour, comment ça va ?"},
        {"palabras": "comment ça va", "oracion": "Comment vas-tu ?"},
        {"palabras": "content", "oracion": "Je suis content."},
        {"palabras": "triste", "oracion": "Je me sens triste."},
        {"palabras": "heureux", "oracion": "Je me sens heureux."},
        {"palabras": "bonjour", "oracion": "bien et toi"},
        {"palabras": "bien et toi", "oracion": "Bien, et toi ?"},
        {"palabras": "déjeuner soupe", "oracion": "Je veux manger une soupe pour le déjeuner"},
        {"palabras": "dîner", "oracion": "Je veux dîner."},
        {"palabras": "petit-déjeuner", "oracion": "Je veux prendre mon petit-déjeuner."},
        {"palabras": "uriner", "oracion": "J'ai besoin d'aller aux toilettes."},
        {"palabras": "déféquer", "oracion": "J'ai besoin d'aller aux toilettes."},
        {"palabras": "boire", "oracion": "J'ai besoin de boire quelque chose."},
        {"palabras": "boire eau", "oracion": "J'ai besoin de boire de l'eau."},
        {"palabras": "boire vin", "oracion": "Je veux boire un verre de vin."},
        {"palabras": "éteindre télévision", "oracion": "Je veux éteindre la télévision."},
        {"palabras": "éteindre ventilateur", "oracion": "Je veux éteindre le ventilateur."},
        {"palabras": "allumer ventilateur", "oracion": "Je veux allumer le ventilateur."},
        {"palabras": "grand-mère faim", "oracion": "Grand-mère a faim."},
        {"palabras": "chien faim", "oracion": "Le chien a faim"},
        {"palabras": "chat faim", "oracion": "Le chat a faim."},
        {"palabras": "lire", "oracion": "J'ai besoin de lire."},
        {"palabras": "lire livre", "oracion": "Je veux lire un livre."},
        {"palabras": "passer livre", "oracion": "Pourrais-tu me passer le livre ?"},
        {"palabras": "musique", "oracion": "Je veux écouter de la musique."},
        {"palabras": "changer chanson", "oracion": "Je veux changer de chanson."},
        {"palabras": "reculer chanson", "oracion": "Je veux revenir à la chanson précédente."},
        {"palabras": "avancer chanson", "oracion": "Je veux avancer la chanson."},
        {"palabras": "batterie charger", "oracion": "J'ai besoin de charger la batterie."},
        {"palabras": "allumer lumière", "oracion": "Je veux allumer la lumière."},
        {"palabras": "éteindre lumière", "oracion": "Je veux éteindre la lumière."},
        {"palabras": "démangeaison dos", "oracion": "J'ai des démangeaisons dans le dos."},
        {"palabras": "douleur pied", "oracion": "J'ai mal au pied."},
        {"palabras": "monter volume musique", "oracion": "Je veux augmenter le volume de la musique."},
        {"palabras": "besoin ophtalmologue", "oracion": "J'ai besoin d'aller chez l'ophtalmologue."},
        {"palabras": "envoyer message", "oracion": "J'ai besoin d'envoyer un message."},
        {"palabras": "envoyer message maman", "oracion": "J'ai besoin d'envoyer un message à ma maman"},
        {"palabras": "visiter", "oracion": "J'ai besoin de rendre visite à quelqu'un."},
        {"palabras": "heure", "oracion": "Quelle heure est-il ?"},
        {"palabras": "un deux trois", "oracion": "123"}
    ]
}

# German data
de_data = {
    "root": [
        {"palabras": "Hunger Nudeln", "oracion": "Ich habe Hunger, ich möchte Nudeln."},
        {"palabras": "Kanal wechseln", "oracion": "Ich möchte den Fernsehkanal wechseln."},
        {"palabras": "Durst", "oracion": "Ich habe Durst, ich muss etwas trinken."},
        {"palabras": "schlafen", "oracion": "Müdigkeit"},
        {"palabras": "Hunger Apfel Birne", "oracion": "Ich habe Hunger, ich möchte einen Apfel und eine Birne"},
        {"palabras": "Hunger Suppe", "oracion": "Ich habe Hunger, ich möchte eine Suppe."},
        {"palabras": "Hunger Makkaroni Käse", "oracion": "Ich habe Hunger, ich möchte Makkaroni mit Käse."},
        {"palabras": "Durst Wasser", "oracion": "Ich habe Durst, ich muss Wasser trinken."},
        {"palabras": "müde", "oracion": "Ich bin müde."},
        {"palabras": "müde schlafen", "oracion": "Ich bin müde, ich muss schlafen gehen."},
        {"palabras": "Medikament nötig", "oracion": "Ich muss meine Medikamente nehmen"},
        {"palabras": "Kanal wechseln nötig", "oracion": "Ich muss den Kanal wechseln."},
        {"palabras": "Kanal wechseln", "oracion": "Ich muss den Kanal wechseln"},
        {"palabras": "Hunger Burger Pommes", "oracion": "Ich habe Hunger, ich möchte einen Burger mit Pommes."},
        {"palabras": "Radio einschalten", "oracion": "Ich möchte das Radio einschalten."},
        {"palabras": "Sender wechseln", "oracion": "Ich möchte den Radiosender wechseln."},
        {"palabras": "Bad", "oracion": "Bad"},
        {"palabras": "Bad", "oracion": "Ich muss auf die Toilette."},
        {"palabras": "Schmerz", "oracion": "Ich habe Schmerzen."},
        {"palabras": "Kopfschmerzen", "oracion": "Mein Kopf tut weh."},
        {"palabras": "Kniemeißel Schmerz", "oracion": "Ich habe Schmerzen im Knie."},
        {"palabras": "nervös", "oracion": "Ich fühle mich nervös."},
        {"palabras": "baden", "oracion": "Ich muss baden."},
        {"palabras": "Hallo", "oracion": "Hallo, wie geht es dir?"},
        {"palabras": "wie geht es dir", "oracion": "Wie geht es dir?"},
        {"palabras": "freue mich", "oracion": "Das freut mich."},
        {"palabras": "traurig", "oracion": "Ich fühle mich traurig."},
        {"palabras": "glücklich", "oracion": "Ich fühle mich glücklich."},
        {"palabras": "hallo", "oracion": "gut und dir"},
        {"palabras": "gut und dir", "oracion": "Gut, und dir?"},
        {"palabras": "Mittagessen Suppe", "oracion": "Ich möchte zu Mittag eine Suppe essen"},
        {"palabras": "Abendessen", "oracion": "Ich möchte zu Abend essen."},
        {"palabras": "frühstücken", "oracion": "Ich möchte frühstücken."},
        {"palabras": "urinieren", "oracion": "Ich muss auf die Toilette."},
        {"palabras": "stuhlgang", "oracion": "Ich muss auf die Toilette."},
        {"palabras": "trinken", "oracion": "Ich muss etwas trinken."},
        {"palabras": "Wasser trinken", "oracion": "Ich muss Wasser trinken."},
        {"palabras": "Wein trinken", "oracion": "Ich möchte ein Glas Wein trinken."},
        {"palabras": "Fernseher ausschalten", "oracion": "Ich möchte den Fernseher ausschalten."},
        {"palabras": "Ventilator ausschalten", "oracion": "Ich möchte den Ventilator ausschalten."},
        {"palabras": "Ventilator einschalten", "oracion": "Ich möchte den Ventilator einschalten."},
        {"palabras": "Oma Hunger", "oracion": "Oma ist hungrig."},
        {"palabras": "Hund Hunger", "oracion": "Der Hund hat Hunger"},
        {"palabras": "Katze Hunger", "oracion": "Die Katze hat Hunger."},
        {"palabras": "lesen", "oracion": "Ich muss lesen."},
        {"palabras": "Buch lesen", "oracion": "Ich möchte ein Buch lesen."},
        {"palabras": "Buch reichen", "oracion": "Könntest du mir das Buch reichen?"},
        {"palabras": "Musik", "oracion": "Ich möchte Musik hören."},
        {"palabras": "Lied wechseln", "oracion": "Ich möchte das Lied wechseln."},
        {"palabras": "Lied zurückspulen", "oracion": "Ich möchte zum vorherigen Lied zurückgehen."},
        {"palabras": "Lied vorspulen", "oracion": "Ich möchte das Lied vorspulen."},
        {"palabras": "Akku laden", "oracion": "Ich muss den Akku aufladen."},
        {"palabras": "Licht einschalten", "oracion": "Ich möchte das Licht einschalten."},
        {"palabras": "Licht ausschalten", "oracion": "Ich möchte das Licht ausschalten."},
        {"palabras": "juckender Rücken", "oracion": "Mein Rücken juckt."},
        {"palabras": "Fußschmerz", "oracion": "Ich habe Schmerzen im Fuß."},
        {"palabras": "Musik lauter machen", "oracion": "Ich möchte die Musik lauter machen."},
        {"palabras": "Augenarzt nötig", "oracion": "Ich muss zum Augenarzt gehen."},
        {"palabras": "Nachricht senden", "oracion": "Ich muss eine Nachricht senden."},
        {"palabras": "Nachricht an Mama senden", "oracion": "Ich muss meiner Mama eine Nachricht senden"},
        {"palabras": "besuchen", "oracion": "Ich muss jemanden besuchen."},
        {"palabras": "Uhrzeit", "oracion": "Wie spät ist es?"},
        {"palabras": "eins zwei drei", "oracion": "123"}
    ]
}

with open('ChineseSentences.json', 'w', encoding='utf-8') as f:
    json.dump(zh_data, f, ensure_ascii=False, indent=4)

with open('KoreanSentences.json', 'w', encoding='utf-8') as f:
    json.dump(ko_data, f, ensure_ascii=False, indent=4)

with open('ItalianSentences.json', 'w', encoding='utf-8') as f:
    json.dump(it_data, f, ensure_ascii=False, indent=4)

with open('FrenchSentences.json', 'w', encoding='utf-8') as f:
    json.dump(fr_data, f, ensure_ascii=False, indent=4)

with open('GermanSentences.json', 'w', encoding='utf-8') as f:
    json.dump(de_data, f, ensure_ascii=False, indent=4)

print("Translations generated successfully.")
